test reverting build destination

diff --git a/.github/workflows/image-build.yml b/.github/workflows/image-build.yml
--- a/.github/workflows/image-build.yml
+++ b/.github/workflows/image-build.yml
@@ -21,9 +21,10 @@ jobs:
   build:
     runs-on: arc-runner-${{ github.event.repository.name }}
     container:
-      image: gcr.io/kaniko-project/executor:debug
+      image: registry.default/randomcoww/kaniko:latest
     permissions:
       contents: read
+      packages: write
     steps:
     - name: Set tag
       run: |
@@ -46,7 +47,7 @@ jobs:
         /kaniko/executor \
           --dockerfile="./Containerfile" \
           --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
-          --destination="$INTERNAL_REGISTRY/${{ github.repository }}:v$TAG" \
+          --destination="ghcr.io/${{ github.repository }}:v$TAG" \
           --registry-certificate=$INTERNAL_REGISTRY=$DOCKER_CONFIG/internal.crt \
           --build-arg BASE_IMAGE=ghcr.io/ggml-org/llama.cpp:server-cuda \
           --image-fs-extract-retry=6 \
@@ -54,23 +55,39 @@ jobs:
   cleanup:
     needs:
       - build
-    env:
-      TAGS_KEEP: 4
     runs-on: arc-runner-${{ github.event.repository.name }}
     container:
-      image: docker.io/regclient/regctl:alpine
+      image: docker.io/node:current-alpine
+    permissions:
+      packages: write
     steps:
-    - name: Remove old tags
-      run: |
-        set -e
-        regctl registry set $INTERNAL_REGISTRY --cacert "$INTERNAL_CA_CERT"
-        tags=$(regctl tag ls $INTERNAL_REGISTRY/${{ github.repository }} | grep -v latest | sort -r)
+      - name: Remove old container images
+        uses: actions/delete-package-versions@v5
+        with:
+          package-name: ${{ github.event.repository.name }}
+          package-type: container
+          min-versions-to-keep: 4
+          token: ${{ secrets.GITHUB_TOKEN }}
+  # cleanup:
+  #   needs:
+  #     - build
+  #   env:
+  #     TAGS_KEEP: 4
+  #   runs-on: arc-runner-${{ github.event.repository.name }}
+  #   container:
+  #     image: docker.io/regclient/regctl:alpine
+  #   steps:
+  #   - name: Remove old tags
+  #     run: |
+  #       set -e
+  #       regctl registry set $INTERNAL_REGISTRY --cacert "$INTERNAL_CA_CERT"
+  #       tags=$(regctl tag ls $INTERNAL_REGISTRY/${{ github.repository }} | grep -v latest | sort -r)
 
-        i=0
-        for tag in $tags; do
-          if [ "$i" -ge "$TAGS_KEEP" ]; then
-            echo "Delete $tag"
-            regctl tag delete --ignore-missing $INTERNAL_REGISTRY/${{ github.repository }}:$tag
-          fi
-          i=$((i + 1))
-        done
+  #       i=0
+  #       for tag in $tags; do
+  #         if [ "$i" -ge "$TAGS_KEEP" ]; then
+  #           echo "Delete $tag"
+  #           regctl tag delete --ignore-missing $INTERNAL_REGISTRY/${{ github.repository }}:$tag
+  #         fi
+  #         i=$((i + 1))
+  #       done
